
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author SUBHANSHU
 */
public class Customer extends javax.swing.JFrame {

    public Customer() {
        initComponents();
        loadCustomers();
    }

    private void loadCustomers() {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12"); Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM customer")) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int cId = rs.getInt("Id");
                String cname = rs.getString("Name");
                String cemail = rs.getString("Mobile_no");
                String cmobile = rs.getString("Email");
                model.addRow(new Object[]{cId, cname, cemail, cmobile});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error loading customers: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Save_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Reset_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        Close_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Customer Records");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 0, 350, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 97, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel3.setText("Moblie Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 182, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 267, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 136, 300, 28));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 300, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 300, 28));

        Save_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        Save_btn.setText("Save");
        Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile_no", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 97, 464, -1));

        Reset_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        Reset_btn.setText("Reset");
        Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, -1, -1));

        Update_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        Close_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        Close_btn.setText("Close");
        Close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All_page_Background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void Close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_btnActionPerformed
        this.dispose();        

    }//GEN-LAST:event_Close_btnActionPerformed

    private void Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_btnActionPerformed

        Connection con = null;
        PreparedStatement pstmt = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // 1️⃣ Get input values
            String name = jTextField1.getText().trim();
            // Mobile number is treated as a String
            String mobileStr = jTextField2.getText().trim();
            String email = jTextField3.getText().trim();

            // 2️⃣ Check required fields
            if (name.isEmpty() || mobileStr.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "⚠ All fields are required!");
                return;
            }

            // ⭐ No validation or Long.parseLong() is used (as requested)
            // 3️⃣ Connect to database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12");

            // 4️⃣ Insert data into table
            String sql = "INSERT INTO customer (Name, Mobile_no, Email) VALUES (?, ?, ?)";
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, name);
            // ⭐ Using setString() now works because the column is VARCHAR(25)
            pstmt.setString(2, mobileStr);
            pstmt.setString(3, email);

            int rows = pstmt.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "✅ Customer added successfully!");

                // 5️⃣ Refresh table
                stmt = con.createStatement();
                rs = stmt.executeQuery("SELECT * FROM customer");

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    int id = rs.getInt("Id");
                    String cname = rs.getString("Name");
                    // ⭐ Retrieve as String
                    String cmobile = rs.getString("Mobile_no");
                    String cemail = rs.getString("Email");
                    model.addRow(new Object[]{id, cname, cmobile, cemail});
                }

                // 6️⃣ Clear fields
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "⚠ Failed to add customer.");
            }

        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "⚠ Duplicate or invalid entry: " + e.getMessage());
        } catch (Exception e) {
            // This will catch the "Data too long" error if the column size is not fixed.
            JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
        } finally {
            // 7️⃣ Close resources
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
            }
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_Save_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed

        Connection con = null;
        PreparedStatement pstmt = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // 1️⃣ Get ID from Selected Table Row
            int selectedRow = jTable1.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "⚠ Please select a customer record from the table to update!");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            // Get the ID from the first column (index 0)
            int id = (int) model.getValueAt(selectedRow, 0);

            // 2️⃣ Get input values
            String name = jTextField1.getText().trim();
            String mobileStr = jTextField2.getText().trim();
            String email = jTextField3.getText().trim();

            // 3️⃣ Conditional Query Building
            StringBuilder sqlBuilder = new StringBuilder("UPDATE customer SET ");
            boolean firstField = true;

            // List to hold the parameter values for the prepared statement
            java.util.List<Object> params = new java.util.ArrayList<>();

            // Check and build the query for Name
            if (!name.isEmpty()) {
                sqlBuilder.append("Name = ?");
                params.add(name);
                firstField = false;
            }

            // Check and build the query for Mobile_no
            if (!mobileStr.isEmpty()) {
                if (!firstField) {
                    sqlBuilder.append(", ");
                }
                sqlBuilder.append("Mobile_no = ?");
                params.add(mobileStr);
                firstField = false;
            }

            // Check and build the query for Email
            if (!email.isEmpty()) {
                if (!firstField) {
                    sqlBuilder.append(", ");
                }
                sqlBuilder.append("Email = ?");
                params.add(email);
                firstField = false;
            }

            // 4️⃣ Final checks and query completion
            if (params.isEmpty()) {
                JOptionPane.showMessageDialog(this, "⚠ No data entered to update. Please fill in at least one field.");
                return;
            }

            // Append WHERE clause and add the ID as the last parameter
            sqlBuilder.append(" WHERE Id = ?");

            String sql = sqlBuilder.toString();

            // 5️⃣ Connect to database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12");

            // 6️⃣ Execute the dynamically built query
            pstmt = con.prepareStatement(sql);

            // Set parameters (Strings first)
            for (int i = 0; i < params.size(); i++) {
                pstmt.setString(i + 1, (String) params.get(i));
            }
            // Set the very last parameter (Id)
            pstmt.setInt(params.size() + 1, id);

            int rows = pstmt.executeUpdate();

            if (rows > 0) {
                // Show success message
                JOptionPane.showMessageDialog(this, "✅ Customer record updated successfully!");

                // 7️⃣ REFRESH TABLE (Your requested code)
                stmt = con.createStatement();
                rs = stmt.executeQuery("SELECT * FROM customer");

                // Clear existing rows
                model.setRowCount(0);

                // Repopulate table with updated data
                while (rs.next()) {
                    int cId = rs.getInt("Id");
                    String cname = rs.getString("Name");
                    String cmobile = rs.getString("Mobile_no");
                    String cemail = rs.getString("Email");
                    model.addRow(new Object[]{cId, cname, cmobile, cemail});
                }

                // 8️⃣ Clear fields
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "⚠ Failed to update customer. ID not found or no changes made.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error during update: " + e.getMessage());
        } finally {
            // 9️⃣ Close resources
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
            }
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTable1.clearSelection();
        loadCustomers();

    }//GEN-LAST:event_Reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_btn;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Save_btn;
    private javax.swing.JButton Update_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
