
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.JTextArea;

/**
 *
 * @author SUBHANSHU
 */
public class Emp_Table extends javax.swing.JFrame {

    /**
     * Creates new form Emp_Table
     */
    public Emp_Table() {
        initComponents();
        loademp();
    }

    private void loademp() {
        try {
            // 1️⃣ Connect to MySQL
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/project", "root", "stcgs@12");
            Statement stmt = con.createStatement();

            // 2️⃣ Disable foreign key checks to avoid constraint error
            stmt.executeUpdate("SET FOREIGN_KEY_CHECKS = 0;");

            // 3️⃣ Reset and renumber emp table
            stmt.executeUpdate("SET @count = 0;");
            stmt.executeUpdate("UPDATE emp SET S_NO = @count := @count + 1;");
            stmt.executeUpdate("ALTER TABLE emp AUTO_INCREMENT = 1;");

            // 4️⃣ Reset and renumber emp_personal table
            stmt.executeUpdate("SET @count = 0;");
            stmt.executeUpdate("UPDATE emp_personal SET S_NO = @count := @count + 1;");
            stmt.executeUpdate("ALTER TABLE emp_personal AUTO_INCREMENT = 1;");

            // 5️⃣ Re-enable foreign key checks
            stmt.executeUpdate("SET FOREIGN_KEY_CHECKS = 1;");

            // 6️⃣ Load Employee (Official) Details into jTable1
            ResultSet rs1 = stmt.executeQuery("SELECT * FROM emp ORDER BY S_NO ASC");
            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            model1.setRowCount(0); // clear old rows

            while (rs1.next()) {
                model1.addRow(new Object[]{
                    rs1.getInt("S_NO"),
                    rs1.getString("Emp_Name"),
                    rs1.getString("Gender"),
                    rs1.getString("Status"),
                    rs1.getDouble("Salary")
                });
            }

            // 7️⃣ Load Employee (Personal) Details into jTable2
            ResultSet rs2 = stmt.executeQuery("SELECT * FROM emp_personal ORDER BY S_NO ASC");
            DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
            model2.setRowCount(0); // clear old rows

            while (rs2.next()) {
                model2.addRow(new Object[]{
                    rs2.getInt("S_NO"),
                    rs2.getString("Address"),
                    rs2.getString("Mobile_No"),
                    rs2.getString("Email")
                });
            }

            // 8️⃣ Close connection and show confirmation
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "⚠️ Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        New_user_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        Search_user_btn = new javax.swing.JButton();
        Edit_Uset_btn = new javax.swing.JButton();
        Delete_User_btn = new javax.swing.JButton();
        Refresh_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("Manage User");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel2.setText(" New Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel3.setText("Edit Information");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        New_user_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        New_user_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        New_user_btn.setText("New User");
        New_user_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        New_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_user_btnActionPerformed(evt);
            }
        });
        getContentPane().add(New_user_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, -1));

        Back_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        Back_btn.setText("Back");
        Back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        Search_user_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Search_user_btn.setText("Search User");
        Search_user_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_user_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Search_user_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, -1));

        Edit_Uset_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Edit_Uset_btn.setText("Edit User");
        Edit_Uset_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edit_Uset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_Uset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Edit_Uset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 210, -1));

        Delete_User_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Delete_User_btn.setText("Delete User");
        Delete_User_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete_User_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_User_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, -1));

        Refresh_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Refresh_btn.setText("Refresh");
        Refresh_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_No", "Emp_Name", "Gender", "Status", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 550, 230));

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_no", "Address", "Phone_no.", "Email"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 550, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All_page_Background.png"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_Back_btnActionPerformed

    private void Edit_Uset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Uset_btnActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select an employee first.");
            return;
        }

        int sno = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/project", "root", "stcgs@12"); Statement stmt = con.createStatement()) {

            // Load emp data
            ResultSet rs = stmt.executeQuery("SELECT * FROM emp WHERE S_no=" + sno);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Employee record not found.");
                rs.close();
                return;
            }

            String name = rs.getString("Emp_Name");
            String gender = rs.getString("Gender");
            String status = rs.getString("Status");
            double salary = rs.getDouble("Salary");
            rs.close();

            // Load personal data
            rs = stmt.executeQuery("SELECT * FROM emp_personal WHERE S_no=" + sno);
            String address = "";
            String phone = "";
            String email = "";
            if (rs.next()) {
                address = rs.getString("Address");
                phone = rs.getString("Mobile_No");
                email = rs.getString("Email");     // UPDATED
            }
            rs.close();

            // -----------------------
            // 1) UPDATE NAME
            // -----------------------
            String newName = JOptionPane.showInputDialog(this, "Enter Name:", name);
            if (newName != null && !newName.trim().isEmpty()
                    && !newName.trim().equals(name == null ? "" : name.trim())) {

                try (PreparedStatement pst = con.prepareStatement(
                        "UPDATE emp SET Emp_Name=? WHERE S_no=?")) {

                    pst.setString(1, newName.trim());
                    pst.setInt(2, sno);
                    pst.executeUpdate();
                }
            }

            // -----------------------
            // 2) UPDATE GENDER
            // -----------------------
            String[] genders = {"Male", "Female", "Other"};
            JComboBox<String> cbGender = new JComboBox<>(genders);

            String genderNorm = (gender == null) ? "" : gender.trim();
            boolean matched = false;

            for (String g : genders) {
                if (g.equalsIgnoreCase(genderNorm)) {
                    cbGender.setSelectedItem(g);
                    matched = true;
                    break;
                }
            }

            if (!matched && !genderNorm.isEmpty()) {
                cbGender.insertItemAt(genderNorm, 0);
                cbGender.setSelectedIndex(0);
            }

            int optG = JOptionPane.showConfirmDialog(
                    this,
                    new Object[]{"Select Gender:", cbGender},
                    "Gender",
                    JOptionPane.OK_CANCEL_OPTION
            );

            if (optG == JOptionPane.OK_OPTION) {
                String selectedGender = cbGender.getSelectedItem().toString().trim();
                if (!selectedGender.equalsIgnoreCase(genderNorm)) {
                    try (PreparedStatement pst = con.prepareStatement(
                            "UPDATE emp SET Gender=? WHERE S_no=?")) {

                        pst.setString(1, selectedGender);
                        pst.setInt(2, sno);
                        pst.executeUpdate();
                    }
                }
            }

            // -----------------------
            // 3) UPDATE STATUS
            // -----------------------
            String[] stats = {"Active", "Inactive"};
            JComboBox<String> cbStatus = new JComboBox<>(stats);

            if (status != null) {
                for (String s : stats) {
                    if (s.equalsIgnoreCase(status.trim())) {
                        cbStatus.setSelectedItem(s);
                        break;
                    }
                }
            }

            int optS = JOptionPane.showConfirmDialog(
                    this,
                    new Object[]{"Select Status:", cbStatus},
                    "Status",
                    JOptionPane.OK_CANCEL_OPTION
            );

            if (optS == JOptionPane.OK_OPTION) {
                String sel = cbStatus.getSelectedItem().toString().trim();
                if (!sel.equalsIgnoreCase(status == null ? "" : status.trim())) {

                    try (PreparedStatement pst = con.prepareStatement(
                            "UPDATE emp SET Status=? WHERE S_no=?")) {

                        pst.setString(1, sel);
                        pst.setInt(2, sno);
                        pst.executeUpdate();
                    }
                }
            }

            // -----------------------
            // 4) UPDATE SALARY
            // -----------------------
            String newSal = JOptionPane.showInputDialog(this, "Enter Salary:", salary);
            if (newSal != null && !newSal.trim().isEmpty()) {
                double salVal = Double.parseDouble(newSal.trim());

                if (salVal != salary) {
                    try (PreparedStatement pst = con.prepareStatement(
                            "UPDATE emp SET Salary=? WHERE S_no=?")) {

                        pst.setDouble(1, salVal);
                        pst.setInt(2, sno);
                        pst.executeUpdate();
                    }
                }
            }

            // -----------------------
            // 5) UPDATE ADDRESS
            // -----------------------
            String newAdd = JOptionPane.showInputDialog(this, "Enter Address:", address);
            if (newAdd != null && !newAdd.trim().isEmpty()
                    && !newAdd.trim().equals(address == null ? "" : address.trim())) {

                try (PreparedStatement pst = con.prepareStatement(
                        "UPDATE emp_personal SET Address=? WHERE S_no=?")) {

                    pst.setString(1, newAdd.trim());
                    pst.setInt(2, sno);
                    pst.executeUpdate();
                }
            }

            // -----------------------
            // 6) UPDATE PHONE
            // -----------------------
            String newPhone = JOptionPane.showInputDialog(this, "Enter Phone:", phone);
            if (newPhone != null && !newPhone.trim().isEmpty()
                    && !newPhone.trim().equals(phone.trim())) {

                try (PreparedStatement pst = con.prepareStatement(
                        "UPDATE emp_personal SET Mobile_No=? WHERE S_no=?")) {

                    pst.setString(1, newPhone.trim());
                    pst.setInt(2, sno);
                    pst.executeUpdate();
                }
            }

            // -----------------------
            // 7) UPDATE EMAIL
            // -----------------------
            String newEmail = JOptionPane.showInputDialog(this, "Enter Email:", email);
            if (newEmail != null && !newEmail.trim().isEmpty()
                    && !newEmail.trim().equals(email == null ? "" : email.trim())) {

                try (PreparedStatement pst = con.prepareStatement(
                        "UPDATE emp_personal SET Email=? WHERE S_no=?")) {

                    pst.setString(1, newEmail.trim());
                    pst.setInt(2, sno);
                    pst.executeUpdate();
                }
            }

            loademp();
            JOptionPane.showMessageDialog(this, "Employee updated.");

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Salary must be a valid number.");
            nf.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_Edit_Uset_btnActionPerformed
    private void Refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_btnActionPerformed
try {
    // 1) Connect to MySQL
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/project", "root", "stcgs@12");
    Statement stmt = con.createStatement();

    // 2) Disable foreign key checks
    stmt.executeUpdate("SET FOREIGN_KEY_CHECKS = 0;");

    // 3) Reset and renumber emp table
    stmt.executeUpdate("SET @count = 0;");
    stmt.executeUpdate("UPDATE emp SET S_NO = @count := @count + 1;");
    stmt.executeUpdate("ALTER TABLE emp AUTO_INCREMENT = 1;");

    // 4) Reset and renumber emp_personal table
    stmt.executeUpdate("SET @count = 0;");
    stmt.executeUpdate("UPDATE emp_personal SET S_NO = @count := @count + 1;");
    stmt.executeUpdate("ALTER TABLE emp_personal AUTO_INCREMENT = 1;");

    // 5) Re-enable foreign key checks
    stmt.executeUpdate("SET FOREIGN_KEY_CHECKS = 1;");

    // 6) Load Employee (Official) Details into jTable1
    ResultSet rs1 = stmt.executeQuery("SELECT * FROM emp ORDER BY S_NO ASC");
    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
    model1.setRowCount(0);

    while (rs1.next()) {
        model1.addRow(new Object[]{
                rs1.getInt("S_NO"),
                rs1.getString("Emp_Name"),
                rs1.getString("Gender"),
                rs1.getString("Status"),
                rs1.getDouble("Salary")
        });
    }

    // 7) Load Employee (Personal) Details into jTable2
    ResultSet rs2 = stmt.executeQuery("SELECT * FROM emp_personal ORDER BY S_NO ASC");
    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    model2.setRowCount(0);

    while (rs2.next()) {
        model2.addRow(new Object[]{
                rs2.getInt("S_NO"),
                rs2.getString("Address"),
                rs2.getString("Mobile_No"),
                rs2.getString("Email")     // UPDATED HERE
        });
    }

    // 8) Close connection
    con.close();
    JOptionPane.showMessageDialog(this, "Data refreshed and S_NO reset successfully!");

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_Refresh_btnActionPerformed

    private void Search_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_user_btnActionPerformed
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");

    Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/project", "root", "stcgs@12");

    String[] options = {"Id_No.", "Name", "Status"};
    String choice = (String) JOptionPane.showInputDialog(
            this,
            "Search employee by:",
            "Search Option",
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]
    );

    if (choice == null) {
        JOptionPane.showMessageDialog(this, "Search cancelled.");
        return;
    }

    String value = JOptionPane.showInputDialog(this, "Enter " + choice + ":");
    if (value == null || value.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No " + choice + " entered.");
        return;
    }

    PreparedStatement pst;

    // Prepare main emp query
    if (choice.equals("Id_No.")) {
        pst = con.prepareStatement("SELECT * FROM emp WHERE S_no = ?");
        pst.setInt(1, Integer.parseInt(value.trim()));
    } else if (choice.equals("Name")) {
        pst = con.prepareStatement("SELECT * FROM emp WHERE Emp_Name = ?");
        pst.setString(1, value.trim());
    } else {
        pst = con.prepareStatement("SELECT * FROM emp WHERE Status = ?");
        pst.setString(1, value.trim());
    }

    ResultSet rs = pst.executeQuery();

    StringBuilder output = new StringBuilder();
    boolean found = false;

    // Clear both tables
    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel(); // emp
    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel(); // emp_personal

    model1.setRowCount(0);
    model2.setRowCount(0);

    while (rs.next()) {

        found = true;

        int sno = rs.getInt("S_no");
        String empName = rs.getString("Emp_Name");
        String gender = rs.getString("Gender");
        String status = rs.getString("Status");
        double salary = rs.getDouble("Salary");

        // Fetch personal info
        PreparedStatement ps = con.prepareStatement("SELECT * FROM emp_personal WHERE S_no = ?");
        ps.setInt(1, sno);
        ResultSet rs2 = ps.executeQuery();

        String address = "", phone = "", email = "";

        if (rs2.next()) {
            address = rs2.getString("Address");
            phone = rs2.getString("Mobile_No");
            email = rs2.getString("Email");
        }

        // Text output
        output.append(
                "S_no       : " + sno + "\n"
                + "Name       : " + empName + "\n"
                + "Gender     : " + gender + "\n"
                + "Status     : " + status + "\n"
                + "Salary     : " + salary + "\n"
                + "--- Personal Info ---\n"
                + "Address    : " + address + "\n"
                + "Phone      : " + phone + "\n"
                + "Email      : " + email + "\n"
                + "------------------------------\n"
        );

        // ADD TO EMP TABLE (jTable1)
        model1.addRow(new Object[]{
            sno, empName, gender, status, salary
        });

        // ADD TO PERSONAL TABLE (jTable2)
        model2.addRow(new Object[]{
            sno, address, phone, email
        });

        rs2.close();
        ps.close();
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "No record found with the given " + choice + ".");
    } else {
        JOptionPane.showMessageDialog(this, output.toString());
    }

    rs.close();
    pst.close();
    con.close();

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_Search_user_btnActionPerformed

    private void New_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_user_btnActionPerformed
        NewEmployeeForm form = new NewEmployeeForm();
        form.setVisible(true);
        form.setLocationRelativeTo(this);
        form.setAlwaysOnTop(true);
    }//GEN-LAST:event_New_user_btnActionPerformed

    private void Delete_User_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_btnActionPerformed
        int[] rows = jTable1.getSelectedRows();  // multiple row selection

        if (rows.length == 0) {
            JOptionPane.showMessageDialog(this, "Select at least one employee.");
            return;
        }

        Connection con = null;
        PreparedStatement pst = null;
        Statement stmt = null;

        try {
            con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/project", "root", "stcgs@12");

            // delete personal first
            pst = con.prepareStatement("DELETE FROM emp_personal WHERE S_no=?");

            for (int row : rows) {
                int sno = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                pst.setInt(1, sno);
                pst.executeUpdate();
            }

            pst.close();

            // delete from emp
            pst = con.prepareStatement("DELETE FROM emp WHERE S_no=?");

            for (int row : rows) {
                int sno = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                pst.setInt(1, sno);
                pst.executeUpdate();
            }

            pst.close();

            stmt = con.createStatement();

            // Reset auto increment (optional)
            stmt.executeUpdate("ALTER TABLE emp AUTO_INCREMENT = 1");
            stmt.executeUpdate("ALTER TABLE emp_personal AUTO_INCREMENT = 1");

            // Refresh emp table
            ResultSet rs1 = stmt.executeQuery("SELECT * FROM emp");
            DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
            m1.setRowCount(0);

            while (rs1.next()) {
                m1.addRow(new Object[]{
                    rs1.getInt("S_no"),
                    rs1.getString("Emp_Name"),
                    rs1.getString("Gender"),
                    rs1.getString("Status"),
                    rs1.getDouble("Salary")
                });
            }

            // Refresh emp_personal table
            ResultSet rs2 = stmt.executeQuery("SELECT * FROM emp_personal");
            DefaultTableModel m2 = (DefaultTableModel) jTable2.getModel();
            m2.setRowCount(0);

            while (rs2.next()) {
                m2.addRow(new Object[]{
                    rs2.getInt("S_no"),
                    rs2.getString("Address"),
                    rs2.getString("Mobile_No"),
                    rs2.getString("Email") // UPDATED HERE
                });
            }

            stmt.close();
            con.close();

            JOptionPane.showMessageDialog(this, "Selected employees deleted.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_Delete_User_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton Delete_User_btn;
    private javax.swing.JButton Edit_Uset_btn;
    private javax.swing.JButton New_user_btn;
    private javax.swing.JButton Refresh_btn;
    private javax.swing.JButton Search_user_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
