/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
 import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author SUBHANSHU
 */
public class P_details extends javax.swing.JFrame {

    public P_details(ResultSet rs) throws Exception {
        initComponents();
       

    }
 private void loadProducts() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM product");   // fixed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            int s_no = rs.getInt("S_no");
            String pName = rs.getString("P_Name");
            double price = rs.getDouble("Price");
            String category = rs.getString("Category");
            int quantity = rs.getInt("Quantity");

            model.addRow(new Object[]{s_no, pName, price, category, quantity});
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading products: " + e.getMessage());
    }
}

 

    /**
     * Creates new form P_details
     */
    public P_details() {
        initComponents();
     loadProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Refresh_btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        Search_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        New_Product_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S_no", "Product_Name", "Price", "Categary", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 510, 500));

        Refresh_btn.setBackground(new java.awt.Color(0, 0, 0));
        Refresh_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Refresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        Refresh_btn.setText("Refresh");
        Refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        Back_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Back_Btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        Back_Btn.setText("Back");
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, -1, -1));

        Update_btn.setBackground(new java.awt.Color(0, 0, 0));
        Update_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Update_btn.setForeground(new java.awt.Color(255, 255, 255));
        Update_btn.setText("Update product");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        Search_btn.setBackground(new java.awt.Color(0, 0, 0));
        Search_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search_btn.setForeground(new java.awt.Color(255, 255, 255));
        Search_btn.setText("Search product");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, 40));

        Delete_btn.setBackground(new java.awt.Color(0, 0, 0));
        Delete_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        Delete_btn.setText("Delete Product");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        jLabel1.setText("Product_Detailed");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        New_Product_btn.setBackground(new java.awt.Color(0, 0, 0));
        New_Product_btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        New_Product_btn.setForeground(new java.awt.Color(255, 255, 255));
        New_Product_btn.setText(" New Product");
        New_Product_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Product_btnActionPerformed(evt);
            }
        });
        getContentPane().add(New_Product_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All_page_Background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
       
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Back_BtnActionPerformed

    private void Refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_btnActionPerformed

   Connection con = null;
Statement stmt = null;
ResultSet rs = null;

try {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12");
    stmt = con.createStatement(); 
        // --- Query all products ---
        String sql = "SELECT * FROM product";
        rs = stmt.executeQuery(sql);

        // --- Get JTable model and clear previous rows ---
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // --- Add rows from database ---
        while (rs.next()) {
            int s_no = rs.getInt("S_no");
            String pName = rs.getString("P_Name");
            double price = rs.getDouble("Price");
            String category = rs.getString("Category");
            int quantity = rs.getInt("Quantity");

            model.addRow(new Object[]{s_no, pName, price, category, quantity});
        }

        JOptionPane.showMessageDialog(this, "✅ Product list refreshed successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception e) {}
        try { if (stmt != null) stmt.close(); } catch (Exception e) {}
        try { if (con != null) con.close(); } catch (Exception e) {}
    }


    }//GEN-LAST:event_Refresh_btnActionPerformed

    private void New_Product_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Product_btnActionPerformed
    Connection con = null;
PreparedStatement pstmt = null;
Statement stmt = null;
ResultSet rs = null;

try {
    // ---------- UI PANEL ----------
    JTextField nameField = new JTextField();
    JTextField priceField = new JTextField();
    JTextField quantityField = new JTextField();

    String[] categories = {"Electronics", "Sports", "Spare Parts"};
    JComboBox<String> categoryBox = new JComboBox<>(categories);

    JPanel panel = new JPanel(new GridLayout(0, 1));
    panel.add(new JLabel("Product Name:"));
    panel.add(nameField);
    panel.add(new JLabel("Price:"));
    panel.add(priceField);
    panel.add(new JLabel("Category:"));
    panel.add(categoryBox);
    panel.add(new JLabel("Quantity:"));
    panel.add(quantityField);

    int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Add New Product",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );

    if (result != JOptionPane.OK_OPTION) {
        JOptionPane.showMessageDialog(this, "Operation cancelled.");
        return;
    }

    String pName = nameField.getText().trim();
    String priceStr = priceField.getText().trim();
    String category = (String) categoryBox.getSelectedItem();
    String quantityStr = quantityField.getText().trim();

    if (pName.isEmpty() || priceStr.isEmpty() || quantityStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required.");
        return;
    }

    double price = Double.parseDouble(priceStr);
    int quantity = Integer.parseInt(quantityStr);

    // ---------- database ----------
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12");
    stmt = con.createStatement();
    
    String sql = "INSERT INTO product (P_Name, Price, Category, Quantity) VALUES (?, ?, ?, ?)";
    pstmt = con.prepareStatement(sql);
    pstmt.setString(1, pName);
    pstmt.setDouble(2, price);
    pstmt.setString(3, category);
    pstmt.setInt(4, quantity);

    int inserted = pstmt.executeUpdate();

    if (inserted > 0) {
        JOptionPane.showMessageDialog(this, "Product added successfully!");

        // refresh table
        stmt = con.createStatement();
        rs = stmt.executeQuery("SELECT * FROM product");

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getInt("S_no"),
                    rs.getString("P_Name"),
                    rs.getDouble("Price"),
                    rs.getString("Category"),
                    rs.getInt("Quantity")
            });
        }
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add product.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
} finally {
    try { if (rs != null) rs.close(); } catch (Exception e) {}
    try { if (stmt != null) stmt.close(); } catch (Exception e) {}
    try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
    try { if (con != null) con.close(); } catch (Exception e) {}
}

    }//GEN-LAST:event_New_Product_btnActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed

     Connection con = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "stcgs@12");
        Statement stmt = con.createStatement();
        
        String[] options = {
                "Search by Name",
                "Search by Category",
                "Search by Price Range + Category + Name"
        };

        int choice = JOptionPane.showOptionDialog(
                this,
                "Choose a search option:",
                "Search Options",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );

        String sql = "";

        // 1. Search by name
        if (choice == 0) {
            String name = JOptionPane.showInputDialog(this, "Enter product name (full or partial):");
            if (name == null || name.trim().isEmpty()) return;

            sql = "SELECT * FROM product WHERE P_Name LIKE ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, "%" + name + "%");
        }

        // 2. Search by category
        else if (choice == 1) {
            String[] categories = {"Electronics", "Sports", "Spare Parts"};
            JComboBox<String> categoryBox = new JComboBox<>(categories);

            int ans = JOptionPane.showConfirmDialog(
                    this,
                    categoryBox,
                    "Select Category",
                    JOptionPane.OK_CANCEL_OPTION
            );
            if (ans != JOptionPane.OK_OPTION) return;

            String category = categoryBox.getSelectedItem().toString();

            sql = "SELECT * FROM product WHERE Category = ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, category);
        }

        // 3. Search by price + category + name
        else if (choice == 2) {

            String minR = JOptionPane.showInputDialog(this, "Enter minimum price:");
            if (minR == null) return;
            double minVal = Double.parseDouble(minR);

            String maxR = JOptionPane.showInputDialog(this, "Enter maximum price:");
            if (maxR == null) return;
            double maxVal = Double.parseDouble(maxR);

            String[] categories = {"Electronics", "Sports", "Spare Parts"};
            JComboBox<String> categoryBox = new JComboBox<>(categories);

            int catAns = JOptionPane.showConfirmDialog(
                    this,
                    categoryBox,
                    "Select Category",
                    JOptionPane.OK_CANCEL_OPTION
            );
            if (catAns != JOptionPane.OK_OPTION) return;

            String category = categoryBox.getSelectedItem().toString();

            String nameFilter = JOptionPane.showInputDialog(this, "Enter part of product name (optional):");
            if (nameFilter == null) nameFilter = "";

            sql = "SELECT * FROM product WHERE Price BETWEEN ? AND ? AND Category = ? AND P_Name LIKE ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setDouble(1, minVal);
            pstmt.setDouble(2, maxVal);
            pstmt.setString(3, category);
            pstmt.setString(4, "%" + nameFilter + "%");
        }

        else return;

        rs = pstmt.executeQuery();

        // Load JTable
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Build table-like text for JOptionPane
        StringBuilder sb = new StringBuilder();
        sb.append("S_no | Name | Price | Category | Quantity\n");
        sb.append("---------------------------------------------\n");

        int count = 0;

        while (rs.next()) {
            int s = rs.getInt("S_no");
            String name = rs.getString("P_Name");
            double price = rs.getDouble("Price");
            String cat = rs.getString("Category");
            int qty = rs.getInt("Quantity");

            model.addRow(new Object[]{s, name, price, cat, qty});

            sb.append(String.format("%d | %s | %.2f | %s | %d\n",
                    s, name, price, cat, qty));

            count++;
        }

        if (count == 0) {
            JOptionPane.showMessageDialog(this, "No records found.");
        } else {
            JTextArea text = new JTextArea(sb.toString());
            text.setEditable(false);
            text.setColumns(50);
            text.setRows(15);
            text.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));

            JScrollPane scroll = new JScrollPane(text);

            JOptionPane.showMessageDialog(
                    this,
                    scroll,
                    "Search Results (" + count + " records)",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception e) {}
        try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
        try { if (con != null) con.close(); } catch (Exception e) {}
    }



    }//GEN-LAST:event_Search_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed

        int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product to delete.");
        return;
    }

    // Read S_no from selected row
    int sNo = (int) jTable1.getValueAt(selectedRow, 0);

    // JDBC variables
    Connection con = null;
    PreparedStatement pstmt = null;
    Statement stmt = null;
    ResultSet rs = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver"); // Make sure MySQL connector is added
        con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/project", "root", "stcgs@12"
        );

        // Delete using S_no
        pstmt = con.prepareStatement("DELETE FROM product WHERE S_no = ?");
        pstmt.setInt(1, sNo);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            // Fix numbering
            stmt = con.createStatement();
            stmt.executeUpdate("SET @a = 0");
            stmt.executeUpdate("UPDATE product SET S_no = @a:=@a+1");
            stmt.executeUpdate("ALTER TABLE product AUTO_INCREMENT = 1");

            // Reload JTable
            rs = stmt.executeQuery("SELECT * FROM product");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("S_no"),
                        rs.getString("P_Name"),
                        rs.getDouble("Price"),
                        rs.getString("Category"),
                        rs.getInt("Quantity")
                });
            }

            JOptionPane.showMessageDialog(this, "Record deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "No record deleted.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception e) {}
        try { if (stmt != null) stmt.close(); } catch (Exception e) {}
        try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
        try { if (con != null) con.close(); } catch (Exception e) {}
    }
 


    }//GEN-LAST:event_Delete_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed

    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product to update.");
        return;
    }

    // Read current values from the selected row
    int sNo = (int) jTable1.getValueAt(selectedRow, 0);
    String oldName = jTable1.getValueAt(selectedRow, 1).toString();
    double oldPrice = Double.parseDouble(jTable1.getValueAt(selectedRow, 2).toString());
    String oldCategory = jTable1.getValueAt(selectedRow, 3).toString();
    int oldQty = Integer.parseInt(jTable1.getValueAt(selectedRow, 4).toString());

    // Text fields for editable fields
    JTextField nameField = new JTextField(oldName);
    JTextField priceField = new JTextField(String.valueOf(oldPrice));
    JTextField qtyField = new JTextField(String.valueOf(oldQty));

    // Combo box for Category
    String[] categories = {"Electronics", "Sports", "Spare Parts"};
    JComboBox<String> categoryBox = new JComboBox<>(categories);
    categoryBox.setSelectedItem(oldCategory);

    // Organize update form
    Object[] form = {
            "Product Name:", nameField,
            "Price:", priceField,
            "Category:", categoryBox,
            "Quantity:", qtyField
    };

    int option = JOptionPane.showConfirmDialog(
            this,
            form,
            "Update Product",
            JOptionPane.OK_CANCEL_OPTION
    );

    if (option != JOptionPane.OK_OPTION) {
        return;
    }

    // Read updated values
    String name = nameField.getText();
    double price = Double.parseDouble(priceField.getText());
    String category = categoryBox.getSelectedItem().toString();
    int qty = Integer.parseInt(qtyField.getText());

    // JDBC connection variables
    Connection con = null;
    PreparedStatement pstmt = null;
    Statement stmt = null;
    ResultSet rs = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");  // Make sure MySQL connector is added
        con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/project", "root", "stcgs@12"
        );

        // Update query
        pstmt = con.prepareStatement(
                "UPDATE product SET P_Name=?, Price=?, Category=?, Quantity=? WHERE S_no=?"
        );
        pstmt.setString(1, name);
        pstmt.setDouble(2, price);
        pstmt.setString(3, category);
        pstmt.setInt(4, qty);
        pstmt.setInt(5, sNo);

        int rows = pstmt.executeUpdate();

        if (rows > 0) {
            // Refresh table
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM product");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("S_no"),
                        rs.getString("P_Name"),
                        rs.getDouble("Price"),
                        rs.getString("Category"),
                        rs.getInt("Quantity")
                });
            }

            JOptionPane.showMessageDialog(this, "Product updated successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception e) {}
        try { if (stmt != null) stmt.close(); } catch (Exception e) {}
        try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
        try { if (con != null) con.close(); } catch (Exception e) {}
    }
 

    }//GEN-LAST:event_Update_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JButton New_Product_btn;
    private javax.swing.JButton Refresh_btn;
    private javax.swing.JButton Search_btn;
    private javax.swing.JButton Update_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
