
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SUBHANSHU
 */
public class Store_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Store_Menu
     */
    public Store_Menu() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_btn = new javax.swing.JButton();
        Product_btn = new javax.swing.JButton();
        Customer_btn = new javax.swing.JButton();
        Veiw_order_btn = new javax.swing.JButton();
        Order_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        User_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        User_btn.setText("User");
        User_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        User_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_btnActionPerformed(evt);
            }
        });
        getContentPane().add(User_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        Product_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Product_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product.png"))); // NOI18N
        Product_btn.setText("Product");
        Product_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        Product_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Product_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        Customer_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Customer_btn.setForeground(new java.awt.Color(0, 51, 51));
        Customer_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        Customer_btn.setText("Customer");
        Customer_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        Customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Customer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        Veiw_order_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Veiw_order_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-orders.png"))); // NOI18N
        Veiw_order_btn.setText("Veiw Order");
        Veiw_order_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        Veiw_order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Veiw_order_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Veiw_order_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        Order_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Order_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Orders.png"))); // NOI18N
        Order_btn.setText("Order");
        Order_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        Order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Order_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        Logout_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        Logout_btn.setText("Logout");
        Logout_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Store.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_btnActionPerformed
        Customer reg = new Customer();
        reg.setVisible(true);
        reg.setLocationRelativeTo(this);
        reg.setAlwaysOnTop(true);


    }//GEN-LAST:event_Customer_btnActionPerformed

    private void User_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_btnActionPerformed

        Emp_Table reg = new Emp_Table();
        reg.setVisible(true);
        reg.setLocationRelativeTo(this);
        reg.setAlwaysOnTop(true);

    }//GEN-LAST:event_User_btnActionPerformed

    private void Veiw_order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Veiw_order_btnActionPerformed
        view_order reg = new view_order();
        reg.setVisible(true);
     
this.dispose();

    }//GEN-LAST:event_Veiw_order_btnActionPerformed

    private void Product_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_btnActionPerformed
        P_details reg = new P_details();
        reg.setVisible(true);
        reg.setLocationRelativeTo(this);
        reg.setAlwaysOnTop(true);

    }//GEN-LAST:event_Product_btnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
       
        Login_page login = new Login_page();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_btnActionPerformed
        order reg = new order();
        reg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Order_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customer_btn;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton Order_btn;
    private javax.swing.JButton Product_btn;
    private javax.swing.JButton User_btn;
    private javax.swing.JButton Veiw_order_btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void Systemexit(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
